### ISSUE TITLE
Rewrite single-cycle `if` into a group

### ISSUE THREAD

**Issue by rachitnigam** [calyxir/calyx#1351]
`if` requires that the given port's value is stable for a cycle. Therefore, if we know that both branches take exactly one cycle, we can rewrite the `if` into a group:
```
static if cond.out { tru } else { fal }
```
into:
```
static group compiled {
  tru[go] = cond.out;
  fal[go] = !cond.out
  compiled[done] = %1
}
```

Borrowing syntax from #1344.

**Comment by rachitnigam** [comment]
This should be done once we enforce that all non-comb-group-associated ports in `if` and `while` are marked `@stable`

**Comment by calebmkim** [comment]
Yep, I'll close this issue. (This was handled in https://github.com/calyxir/calyx/pull/1734)
