### ISSUE TITLE
Allow non-decimal values in parameters (e.g. `std_const`)

### ISSUE THREAD

**Issue by EclecticGriffin** [calyxir/calyx#1362]
Also from the discussion here: https://github.com/cucapra/calyx/discussions/1356

The parser currently only allows for decimal values to be given. The best solution would be to adjust the parser to allow other constant forms (hex, binary, octal, etc) and convert those directly into `u64` in the parser token generation rather than altering the IR constructs.

**Comment by EclecticGriffin** [comment]
Seeing as this isn't really a priority for anyone, we could potentially close this. @bcarlet did you still want this ability? If not feel free to close this out

**Comment by bcarlet** [comment]
I don't think this is really needed; I'll close it.
