### ISSUE TITLE
Another Compaction Bug (Sorry)

### ISSUE THREAD

**Issue by calebmkim** [calyxir/calyx#1909]
I just realized my fix for #1852 still leaves another bug.

Suppose we have a component foo that is `@promotable`

```
component foo (@promotable(4) @go go, ...) -> (...)
```
If we compact the following `seq`

```
@promotable(5) seq {
  @promotable(4) invoke foo()().
  @promotable(1) write_to_reg;
}
```
this means that we _need_ `foo` to be `static`, since compaction involves taking `@promotable -> static<n>` control. (Also, any components that `foo` instantiates now also need to be promoted to `static`). 
However, the decision to make `foo`--or any other component--static doesn't happen until the `static-promotion` pass, which runs after compaction. There's nothing in the promotion pass that forces `foo` to be static.   

## Solution/Future Direction 

1. One solution could be to merge compaction and promotion passes, since they are philisophically doing the same thing (converting dynamic code to static code). One reason why I don't think this is actually too bad is that most of the analysis in the compaction pass is externalized to analyses. In fact, if you look at the code of the `finish_seq` function for both compaction and promotion, there are actually some similarities: they basically iterate thru the existing `seq`, but the actual conversion of the `seq` to `static control` is outsourced to a separate function. 

2. Another solution is, in the compaction pass, to keep a list of all the components we have committed to promotion (i.e., all the components whose go port was written to in a seq that we compacted). At the end, we attach an attribute to all the components that must be static, and the promotion pass must promote them. This will lead to more aggressive promotion than before. 

I'm still not 100% sure which solution is better, so I'd be happy to hear other people's thoughts. 

Either way, there’s still the overall question of how to apply the promotion heuristics. I propose that, long-term, there should be some sort of universal promotion heuristic that applies to both compaction and promotion, while in the short term, we apply compaction aggressively (that is what we are doing currently), while performing generic promotion based on the heuristics.

**Comment by rachitnigam** [comment]
I think a similar problem came up during our synchronous meeting. One of the things I said is that promotion decisions need to be committed before they are allowed to influence other components so maybe that is a possible solution? I think merging is not a very scalable solution if we want other passes to exist in the pipeline between static inference and promotion.

**Comment by calebmkim** [comment]
After a synchronous discussion last Thursday, we couldn't really come up with any other solution besides merging the passes. (The reason(s) are outlined in the above comment)

We agreed to the following plan: try to externalize compaction into an analysis, and merge compaction and promotion. This way, if we decide that the passes are better separate, hopefully it will be less effort to merge them.

**Comment by rachitnigam** [comment]
Okay, sounds good! Thanks for thinking about this. I think a good litmus test for this merge is figuring out another pass that needs to live between inference and promotion (i.e. one that relies on control programs that can be rescheduled) and seeing what kind of interface it needs to use.

**Comment by rachitnigam** [comment]
Interesting! I wonder if this pattern can be abstracted into a little trait that overrides the visitor methods and does this fixup for the pass.

Then, instead of implementing Visitor, a user could implement that trait and rely on the overridden methods to do the right thing.

**Comment by calebmkim** [comment]
Yeah, I think this makes sense to me. One question about what you had in mind (correct me if any of my assumptions are wrong): 

It seems like we want to be able to provide whoever is writing the pass with all of the familiar functions, like `start_seq`, `finish_seq`, `enable`, etc. However, right before `start_seq`, `finish_seq`, etc. is run, we want to run `fixup-timing` right before it (We should also run `fixup-timing` right before and right after each time we visit the component's control). 
This makes it seem like there would be a some repeated code between the Visitor Trait, and this new trait, which is fine?
