### ISSUE TITLE
Update Rust version in CI

### ISSUE THREAD

**Issue by sgpthomas** [calyxir/calyx#1923]
It looks like we pin rust version 1.69.0 for `rustfmt` and `clippy` checks. Is there a reason that we pin this version? or have we just not updated it in a little while.

For the LSP stuff, I'm using return position Impl in traits (from v1.75) and `Option::is_some_and` from v1.70. Can we bump the version? or should I rewrite to not use these features

**Comment by rachitnigam** [comment]
Nope, no particular reason! We will also need to bump the minimum version in the Dockerfile

**Comment by rachitnigam** [comment]
Closed by #1925
