### ISSUE TITLE
Change well-formedness check to allow for toplevel `ref` memories

### ISSUE THREAD

**Issue by nathanielnrn** [calyxir/calyx#1933]
As part of #1932 and #1733 we probably want to allow toplevel modules to contain `ref` memories and still be considered wellformed. Perhaps only if we designate that we wish to compile for synthesis/AXI wrapped. Not sure where this well-formed check lives as of writing.

**Comment by sampsyo** [comment]
The check lives here!
https://github.com/calyxir/calyx/blob/f52e552e1857a000a2cac66f878acdd18bd4ebe5/calyx-opt/src/passes/well_formed.rs#L99-L109

I say we can just delete this. No fuss, no muss.

**Comment by nathanielnrn** [comment]
Closed via #1952
