### ISSUE TITLE
Builder: Support for Combinational Components

### ISSUE THREAD

**Issue by anshumanmohan** [calyxir/calyx#2047]
Calyx allows [combinational components](https://docs.calyxir.org/lang/ref.html?combinational-components#combinational-components), but the eDSL does not appear to support these. Often I have found that a gap in the builder is _just_ a gap in [`builder.py`](https://github.com/calyxir/calyx/blob/main/calyx-py/calyx/builder.py), and that [`py_ast.py`](https://github.com/calyxir/calyx/blob/main/calyx-py/calyx/py_ast.py) actually has support for the feature. The fix is then easy. 

In this case I don't think `py_ast.py` supports combinational components, so I'm making a little issue to discuss. Is this known to be a bad idea? Any thoughts or tips, or is this just a simple omission that I can take a swing at?

**Comment by rachitnigam** [comment]
Simple omission! Go for it
