### ISSUE TITLE
Combinational memories in `gen_exp` and `gen_ntt_pipeline`

### ISSUE THREAD

**Issue by anshumanmohan** [calyxir/calyx#2062]
In exactly two places, we use the eDSL to generate combinational and not sequential memories. These are `gen_exp` and `gen_ntt_pipeline`. We have discussed that we should use default to sequential memories, and use combinational memories only when we know that the memory is very small. I just wanted to flag these two cases in case we want to revisit them. Porting them over will be very easy.

_Originally posted by @anshumanmohan in https://github.com/calyxir/calyx/issues/2052#issuecomment-2128007259_

**Comment by rachitnigam** [comment]
We should use `seq_mem`s instead.
