### ISSUE TITLE
[Cider Dap] Generate metadata table for Calyx Programs directly

### ISSUE THREAD

**Issue by EclecticGriffin** [calyxir/calyx#2183]
We should write a compiler pass to generate the metadata table for calyx-to-calyx debugging and invoke it in cases when we create a debugger with no attached metadata table.

**Comment by rachitnigam** [comment]
#2091 marked this as complete so I assume this is done? If not, remove the stale label please!

**Comment by EclecticGriffin** [comment]
Yup this is done! It managed to escape being marked as closed it seems
