### ISSUE TITLE
Queues: convert to Python library

### ISSUE THREAD

**Issue by anshumanmohan** [calyxir/calyx#2186]
Our queue frontend is getting larger and larger, and is totally polluting the `calyx-py` directory. Let us move it all into its own directory, and in doing so let us convert it into a Python library. Doing so will also make imports easier. In doing all this, let us make sure that the queues still get tested via `runt`. At present they get tested somewhat automatically because they live under `calyx-py/test/correctness/...`.

**Comment by rachitnigam** [comment]
I would recommend putting it in the frontends folder
